config/routes.rb
Rails.application.routes.draw do


  resources :blog_posts
  
  get 'index' => 'practice#index'

  post 'index' => 'practice#index'

  get 'about' => 'practice#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]

  # GET /blog_posts
  # GET /blog_posts.json
  def index
    @blog_posts = BlogPost.all
  end

  # GET /blog_posts/1
  # GET /blog_posts/1.json
  def show
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
  end

  # GET /blog_posts/1/edit
  def edit
  end

  # POST /blog_posts
  # POST /blog_posts.json
  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully created.' }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1
  # PATCH/PUT /blog_posts/1.json
  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1
  # DELETE /blog_posts/1.json
  def destroy
    @blog_post.destroy
    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: 'Blog post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_post_params
      params.require(:blog_post).permit(:title, :author, :blog_entry)
    end
end

app/controllers/practice_controller.rb
class PracticeController < ApplicationController
  def index
  	 # we're not using any variables in the view
        # so nothing to setup in here...yet...
        @name = params[:name]
  end

  def about
  	 # here we'll pull from the query string
        # and save that value in an instance variable
        @color = params[:color]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/practice_helper.rb
module PracticeHelper
end

app/views/blog_posts/_form.html.erb
<%= form_for(blog_post) do |f| %>
  <% if blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
      <% blog_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>

  <div class="field">
    <%= f.label :blog_entry %>
    <%= f.text_area :blog_entry %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Editing Blog Post</h1>

<%= render 'form', blog_post: @blog_post %>

<%= link_to 'Show', @blog_post %> |
<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/index.html.erb
<p id="notice"><%= notice %></p>

<nav class="navbar navbar-default" id="nav">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="  #bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Blog</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Have an account? Log in <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Name</a></li>
            <li><a href="#">Password</a></li>
            <li><a href="#">Boot-Camp</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Email</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>



<h1>Blog Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Blog entry</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blog_posts.each do |blog_post| %>
      <tr>
        <td><%= blog_post.title %></td>
        <td><%= blog_post.author %></td>
        <td><%= blog_post.blog_entry %></td>
        <td><%= link_to 'Show', blog_post %></td>
        <td><%= link_to 'Edit', edit_blog_post_path(blog_post) %></td>
        <td><%= link_to 'Destroy', blog_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog Post', new_blog_post_path %>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>

<%= render 'form', blog_post: @blog_post %>

<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog_post.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @blog_post.author %>
</p>

<p>
  <strong>Blog entry:</strong>
  <%= @blog_post.blog_entry %>
</p>

<%= link_to 'Edit', edit_blog_post_path(@blog_post) %> |
<%= link_to 'Back', blog_posts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ttblog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/practice/about.html.erb
<!-- Remember, internal stylesheet is not the best
    but we have no way to get a Ruby instance
    variable into a CSS file, so we don't have
    much of an alternative here -->



<style>

    #color_me_in {
        background-color: <%= @color %>;
        color: white;
        width: 250px;
        height: 250px;
    }

</style>

<div id="color_me_in">
		<%= @color.uppercase %> BOX ACTIVATED!
    </div>

 <p>

   <%= form_tag index_path do %>

    <%= text_field_tag :name, nil, placeholder: "What's your name?" %>
   	<%= submit_tag "Back to Index" %>

	<% end %>

</p>

app/views/practice/index.html.erb
<h1>Choose</h1>


<% if !@name.nil? %>
	<h2>Welcome Back, <%= @name %></h2>
<% end %>

<% @colors.each do |color| %>
	<p>
		<%= link_to color, about_path(color: color) %>
	</p>
<% end %>